spring.application.name=SIMAC

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_Simac
spring.datasource.username=postgres
spring.datasource.password=123456789

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081


# JWT
jwt.secret=ZmFrZUtleUZvckRldkVudmlyb25tZW50T25seU5vdEZvclByb2R1Y3Rpb25Vc2FnZQ==
jwt.expiration=86400000


# Email (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hanen.bennaceur@esprit.tn
spring.mail.password=etrj ocsw ltkb hpwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


odoo.url=http://localhost:8069
odoo.db=simac
odoo.username=hanenbennaceur115@gmail.com
odoo.password=123456789

#ia
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=mistral